using Xunit;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Todoist.Api;
using Todoist.Model;
using Todoist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Todoist.Test.Model
{
    /// <summary>
    ///  Class for testing Collaborator
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CollaboratorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Collaborator
        //private Collaborator instance;

        public CollaboratorTests()
        {
            // TODO uncomment below to create an instance of Collaborator
            //instance = new Collaborator();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Collaborator
        /// </summary>
        [Fact]
        public void CollaboratorInstanceTest()
        {
            // TODO uncomment below to test "IsType" Collaborator
            //Assert.IsType<Collaborator>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

    }

}
