using Xunit;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Todoist.Api;
using Todoist.Model;
using Todoist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Todoist.Test.Model
{
    /// <summary>
    ///  Class for testing Due
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DueTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Due
        //private Due instance;

        public DueTests()
        {
            // TODO uncomment below to create an instance of Due
            //instance = new Due();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Due
        /// </summary>
        [Fact]
        public void DueInstanceTest()
        {
            // TODO uncomment below to test "IsType" Due
            //Assert.IsType<Due>(instance);
        }


        /// <summary>
        /// Test the property 'String'
        /// </summary>
        [Fact]
        public void StringTest()
        {
            // TODO unit test for the property 'String'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Recurring'
        /// </summary>
        [Fact]
        public void RecurringTest()
        {
            // TODO unit test for the property 'Recurring'
        }
        /// <summary>
        /// Test the property 'Datetime'
        /// </summary>
        [Fact]
        public void DatetimeTest()
        {
            // TODO unit test for the property 'Datetime'
        }
        /// <summary>
        /// Test the property 'Timezone'
        /// </summary>
        [Fact]
        public void TimezoneTest()
        {
            // TODO unit test for the property 'Timezone'
        }

    }

}
