using Xunit;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Todoist.Api;
using Todoist.Model;
using Todoist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Todoist.Test.Model
{
    /// <summary>
    ///  Class for testing Project
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProjectTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Project
        //private Project instance;

        public ProjectTests()
        {
            // TODO uncomment below to create an instance of Project
            //instance = new Project();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Project
        /// </summary>
        [Fact]
        public void ProjectInstanceTest()
        {
            // TODO uncomment below to test "IsType" Project
            //Assert.IsType<Project>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'CommentCount'
        /// </summary>
        [Fact]
        public void CommentCountTest()
        {
            // TODO unit test for the property 'CommentCount'
        }
        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Fact]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Fact]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }
        /// <summary>
        /// Test the property 'Shared'
        /// </summary>
        [Fact]
        public void SharedTest()
        {
            // TODO unit test for the property 'Shared'
        }
        /// <summary>
        /// Test the property 'SyncId'
        /// </summary>
        [Fact]
        public void SyncIdTest()
        {
            // TODO unit test for the property 'SyncId'
        }
        /// <summary>
        /// Test the property 'Favorite'
        /// </summary>
        [Fact]
        public void FavoriteTest()
        {
            // TODO unit test for the property 'Favorite'
        }
        /// <summary>
        /// Test the property 'InboxProject'
        /// </summary>
        [Fact]
        public void InboxProjectTest()
        {
            // TODO unit test for the property 'InboxProject'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
