using Xunit;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Todoist.Api;
using Todoist.Model;
using Todoist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Todoist.Test.Model
{
    /// <summary>
    ///  Class for testing SectionUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SectionUpdateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SectionUpdate
        //private SectionUpdate instance;

        public SectionUpdateTests()
        {
            // TODO uncomment below to create an instance of SectionUpdate
            //instance = new SectionUpdate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SectionUpdate
        /// </summary>
        [Fact]
        public void SectionUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsType" SectionUpdate
            //Assert.IsType<SectionUpdate>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
