using Xunit;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Todoist.Api;
using Todoist.Model;
using Todoist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Todoist.Test.Model
{
    /// <summary>
    ///  Class for testing TaskUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TaskUpdateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TaskUpdate
        //private TaskUpdate instance;

        public TaskUpdateTests()
        {
            // TODO uncomment below to create an instance of TaskUpdate
            //instance = new TaskUpdate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TaskUpdate
        /// </summary>
        [Fact]
        public void TaskUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsType" TaskUpdate
            //Assert.IsType<TaskUpdate>(instance);
        }


        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'LabelIds'
        /// </summary>
        [Fact]
        public void LabelIdsTest()
        {
            // TODO unit test for the property 'LabelIds'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Fact]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }
        /// <summary>
        /// Test the property 'DueString'
        /// </summary>
        [Fact]
        public void DueStringTest()
        {
            // TODO unit test for the property 'DueString'
        }
        /// <summary>
        /// Test the property 'DueDate'
        /// </summary>
        [Fact]
        public void DueDateTest()
        {
            // TODO unit test for the property 'DueDate'
        }
        /// <summary>
        /// Test the property 'DueDatetime'
        /// </summary>
        [Fact]
        public void DueDatetimeTest()
        {
            // TODO unit test for the property 'DueDatetime'
        }
        /// <summary>
        /// Test the property 'DueLang'
        /// </summary>
        [Fact]
        public void DueLangTest()
        {
            // TODO unit test for the property 'DueLang'
        }
        /// <summary>
        /// Test the property 'Assignee'
        /// </summary>
        [Fact]
        public void AssigneeTest()
        {
            // TODO unit test for the property 'Assignee'
        }

    }

}
