using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Todoist.Client;
using Todoist.Api;
// uncomment below to import models
//using Todoist.Model;

namespace Todoist.Test.Api
{
    /// <summary>
    ///  Class for testing CommentsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CommentsApiTests : IDisposable
    {
        private CommentsApi instance;

        public CommentsApiTests()
        {
            instance = new CommentsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CommentsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' CommentsApi
            //Assert.IsType<CommentsApi>(instance);
        }

        /// <summary>
        /// Test CreateComment
        /// </summary>
        [Fact]
        public void CreateCommentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xRequestId = null;
            //NewComment newComment = null;
            //var response = instance.CreateComment(xRequestId, newComment);
            //Assert.IsType<Comment>(response);
        }

        /// <summary>
        /// Test DeleteComment
        /// </summary>
        [Fact]
        public void DeleteCommentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long commentId = null;
            //instance.DeleteComment(commentId);
        }

        /// <summary>
        /// Test GetComment
        /// </summary>
        [Fact]
        public void GetCommentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long commentId = null;
            //var response = instance.GetComment(commentId);
            //Assert.IsType<Comment>(response);
        }

        /// <summary>
        /// Test GetComments
        /// </summary>
        [Fact]
        public void GetCommentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long taskId = null;
            //long? projectId = null;
            //var response = instance.GetComments(taskId, projectId);
            //Assert.IsType<List<Comment>>(response);
        }

        /// <summary>
        /// Test UpdateComment
        /// </summary>
        [Fact]
        public void UpdateCommentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long commentId = null;
            //string xRequestId = null;
            //CommentUpdate commentUpdate = null;
            //instance.UpdateComment(commentId, xRequestId, commentUpdate);
        }
    }
}
