using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Todoist.Client;
using Todoist.Api;
// uncomment below to import models
//using Todoist.Models;

namespace Todoist.Test.Api
{
    /// <summary>
    ///  Class for testing SectionsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SectionsApiTests : IDisposable
    {
        private SectionsApi instance;

        public SectionsApiTests()
        {
            instance = new SectionsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SectionsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SectionsApi
            //Assert.IsType<SectionsApi>(instance);
        }

        /// <summary>
        /// Test CreateSection
        /// </summary>
        [Fact]
        public void CreateSectionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xRequestId = null;
            //NewSection newSection = null;
            //var response = instance.CreateSection(xRequestId, newSection);
            //Assert.IsType<Section>(response);
        }

        /// <summary>
        /// Test DeleteSection
        /// </summary>
        [Fact]
        public void DeleteSectionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long sectionId = null;
            //instance.DeleteSection(sectionId);
        }

        /// <summary>
        /// Test GetSection
        /// </summary>
        [Fact]
        public void GetSectionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long sectionId = null;
            //var response = instance.GetSection(sectionId);
            //Assert.IsType<Section>(response);
        }

        /// <summary>
        /// Test GetSections
        /// </summary>
        [Fact]
        public void GetSectionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetSections();
            //Assert.IsType<List<Section>>(response);
        }

        /// <summary>
        /// Test UpdateSection
        /// </summary>
        [Fact]
        public void UpdateSectionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long sectionId = null;
            //string xRequestId = null;
            //SectionUpdate sectionUpdate = null;
            //instance.UpdateSection(sectionId, xRequestId, sectionUpdate);
        }
    }
}
