using Xunit;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Todoist.Api;
using Todoist.Models;
using Todoist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Todoist.Test.Model
{
    /// <summary>
    ///  Class for testing CommentUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CommentUpdateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CommentUpdate
        //private CommentUpdate instance;

        public CommentUpdateTests()
        {
            // TODO uncomment below to create an instance of CommentUpdate
            //instance = new CommentUpdate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CommentUpdate
        /// </summary>
        [Fact]
        public void CommentUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsType" CommentUpdate
            //Assert.IsType<CommentUpdate>(instance);
        }


        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

    }

}
