using Xunit;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Todoist.Api;
using Todoist.Models;
using Todoist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Todoist.Test.Model
{
    /// <summary>
    ///  Class for testing LabelUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LabelUpdateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LabelUpdate
        //private LabelUpdate instance;

        public LabelUpdateTests()
        {
            // TODO uncomment below to create an instance of LabelUpdate
            //instance = new LabelUpdate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LabelUpdate
        /// </summary>
        [Fact]
        public void LabelUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsType" LabelUpdate
            //Assert.IsType<LabelUpdate>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Fact]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Fact]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }
        /// <summary>
        /// Test the property 'Favorite'
        /// </summary>
        [Fact]
        public void FavoriteTest()
        {
            // TODO unit test for the property 'Favorite'
        }

    }

}
