using Xunit;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Todoist.Api;
using Todoist.Models;
using Todoist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Todoist.Test.Model
{
    /// <summary>
    ///  Class for testing NewComment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NewCommentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NewComment
        //private NewComment instance;

        public NewCommentTests()
        {
            // TODO uncomment below to create an instance of NewComment
            //instance = new NewComment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NewComment
        /// </summary>
        [Fact]
        public void NewCommentInstanceTest()
        {
            // TODO uncomment below to test "IsType" NewComment
            //Assert.IsType<NewComment>(instance);
        }


        /// <summary>
        /// Test the property 'TaskId'
        /// </summary>
        [Fact]
        public void TaskIdTest()
        {
            // TODO unit test for the property 'TaskId'
        }
        /// <summary>
        /// Test the property 'ProjectId'
        /// </summary>
        [Fact]
        public void ProjectIdTest()
        {
            // TODO unit test for the property 'ProjectId'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }
        /// <summary>
        /// Test the property 'Attachment'
        /// </summary>
        [Fact]
        public void AttachmentTest()
        {
            // TODO unit test for the property 'Attachment'
        }

    }

}
