using Xunit;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Todoist.Api;
using Todoist.Models;
using Todoist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Todoist.Test.Model
{
    /// <summary>
    ///  Class for testing NewProject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NewProjectTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NewProject
        //private NewProject instance;

        public NewProjectTests()
        {
            // TODO uncomment below to create an instance of NewProject
            //instance = new NewProject();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NewProject
        /// </summary>
        [Fact]
        public void NewProjectInstanceTest()
        {
            // TODO uncomment below to test "IsType" NewProject
            //Assert.IsType<NewProject>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ParentId'
        /// </summary>
        [Fact]
        public void ParentIdTest()
        {
            // TODO unit test for the property 'ParentId'
        }
        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Fact]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }
        /// <summary>
        /// Test the property 'Favorite'
        /// </summary>
        [Fact]
        public void FavoriteTest()
        {
            // TODO unit test for the property 'Favorite'
        }

    }

}
