using Xunit;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Todoist.Api;
using Todoist.Models;
using Todoist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Todoist.Test.Model
{
    /// <summary>
    ///  Class for testing NewSection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NewSectionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NewSection
        //private NewSection instance;

        public NewSectionTests()
        {
            // TODO uncomment below to create an instance of NewSection
            //instance = new NewSection();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NewSection
        /// </summary>
        [Fact]
        public void NewSectionInstanceTest()
        {
            // TODO uncomment below to test "IsType" NewSection
            //Assert.IsType<NewSection>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ProjectId'
        /// </summary>
        [Fact]
        public void ProjectIdTest()
        {
            // TODO unit test for the property 'ProjectId'
        }
        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Fact]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }

    }

}
