using Xunit;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Todoist.Api;
using Todoist.Models;
using Todoist.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Todoist.Test.Model
{
    /// <summary>
    ///  Class for testing ProjectUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProjectUpdateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProjectUpdate
        //private ProjectUpdate instance;

        public ProjectUpdateTests()
        {
            // TODO uncomment below to create an instance of ProjectUpdate
            //instance = new ProjectUpdate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProjectUpdate
        /// </summary>
        [Fact]
        public void ProjectUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProjectUpdate
            //Assert.IsType<ProjectUpdate>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Fact]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }
        /// <summary>
        /// Test the property 'Favorite'
        /// </summary>
        [Fact]
        public void FavoriteTest()
        {
            // TODO unit test for the property 'Favorite'
        }

    }

}
